### ISSUE TITLE
Repair the anchor elements @type="report" that are missing an @synch

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/Amadis-in-Translation#20]
@setriplette Since our use of @type="report" on the anchor element is kind of new, I just discovered a small but easily correctable problem! In some of the Southey files, where you've applied @type="report", you've NOT applied an @synch to point to the corresponding passage in Montalvo--but we're going to need that to be able to locate the corresponding passage(s) of direct speech in Montalvo! 

It's not consistent, but I notice (I think) in just about every Southey file, there are some of these anchors with @type="report" missing their @synch. So, I've added a new Schematron rule to help us find and fix them all. Stacey, would you do the following ASAP? 
1. Sync your GitHub repository so you have the re-organized project files and new schema
2. Run through each of the Southey files you've stitched (now sitting in their official file locations in the Southey folder): Open them in oXygen and click on the big red validation checkmark (next to the XPath window), and see if there are any validation errors. Click on each error to zoom to it and repair it (and indicate the location in Montalvo that these should be pointing to, and re-validate (click the red checkmark again) to be sure that all is well.
3. Save and push your repairs to GitHub. 

Thanks--let me know if the new file directory structure is confusing or if you had something else in mind for these elements!

**Comment by setriplette** [comment]
This is going to sound idiotic, but it took me two chapters to figure out that I could code a synch AND a report. The ones missing their synch were done last week.

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 2, 2015, at 2:46 AM, brookestewart <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #20https://github.com/ebeshero/Amadis-in-Translation/issues/20 to @setriplettehttps://github.com/setriplette.

**Comment by setriplette** [comment]
I fixed these. Thanks for the clear instructions, Elisa--it was very easy to do.

**Comment by ebeshero** [comment]
Yay! Thanks, Stacey! :+1:
