### ISSUE TITLE
How do I tag Southey turning indirect discourse into direct?

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#22]
The unexpected has happened, and we have an indirect discourse in Montalvo that is (!) a direct discourse in Southey. Thoughts for how to tag this? I'm just putting a comment at present.

**Comment by HelenaSabel** [comment]
To be consistent with the "report" type, I'd just add a "direct" value. I'll change the schematron rule so you can add that new value and if we then change our minds about it, it'll be a quick fix.
