### ISSUE TITLE
appy-templates

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#25]
The way I introduce Southey text in the HTML visualization is by matching and `anchor[@ana='start']` and applying templates to:

 `<xsl:apply-templates
       select="current()/following::node() except current()/following::node()[@ana = 'end'][1]/following::node()"/>`

The reason I get the duplications is because my rule is applying templates to both the node `<persName>` (so it gives us its text content) and to the text node that contents... (same happens with `note`).
I could avoid the duplications on the tables, but I was using `<xsl:value-of >` and I could add `text()` to `current()/following::node()`. However the same strategy wouldn't work here because I do need to apply the templates to those elements. 
Any idea on how can I solve this?

**Comment by ebeshero** [comment]
@HelenaSabel I'm working on it. I made my own copy of your XSLT and changed to my preferred notation of Attribute Value Templates. No improvement yet--I'm heading in to teach now. But I think I know how to fix it, so you can leave it to me.

**Comment by HelenaSabel** [comment]
Thank you, Elisa! I've been working on it, but couldn't find the solution...
