### ISSUE TITLE
HTML keywords

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#31]
Definition of keywords for search engines:

`<meta name="keywords" content="Amadis of Gaule, Amadís de Gaula, Garci Rodríguez de Montalvo, Robert Southey, TEI, Text Encoding Initiative, romance of chivalry, libro de caballerías, libro de caballería, digital humanities, dh, textual scholarship, digital scholarship, translation studies, studies in translation"/>`

What else?

**Comment by setriplette** [comment]
How about the genre words? Romance of chivalry for English, libro de caballerías in Spanish. Also libro de caballería, as there’s a debate as to whether it should be singular or plural (but singular is wrong).

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 20, 2015, at 10:51 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

Definition of keywords for search engines:

<meta name="keywords" content="Amadis of Gaule, Amadís de Gaula, Garci Rodríguez de Montalvo, Robert Southey, TEI">

What else?

**Comment by HelenaSabel** [comment]
Good idea! I'm editing the original issue in Github to add those ("libro de caballería" sounds very peculiar to me).

**Comment by ebeshero** [comment]
Added to the index page, and posted!

**Comment by ebeshero** [comment]
I'm adding a few more, generic meta terms:
digital humanities, dh, textual scholarship, digital scholarship, translation studies, studies in translation
