### ISSUE TITLE
found and corrected a typo in M1

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#32]
Helena, could you reprocess the table?

**Comment by ebeshero** [comment]
@HelenaSabel I've been going over your tables with Stacey, and we're finding they are really clear and readable! And Stacey spotted a typo in her Montalvo code from scanning the table--so it was really useful. Thank you! More on the tables and the FS code in a minute: I'm posting a slightly altered version of your fs-S2.xml in which I've set it so the fs for a note is nested with a Southey feature in the main text.

**Comment by HelenaSabel** [comment]
Done! I'm going to comment on your commit now, so I can explain some of the problems I have...
