### ISSUE TITLE
Found and corrected mistake in Southey 21

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#33]
Helena, can you rerun the table for Montalvo 20/ Southey 21? I found and corrected a mistake in the translation stitching. It's amazing what visualizations can do!

**Comment by HelenaSabel** [comment]
Done!

**Comment by HelenaSabel** [comment]
By the way, whenever you correct something, I also update the feature structures files, so don't be afraid of having anything outdated ;-)
