### ISSUE TITLE
Note in Southey 21?

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#34]
Helena, I've noticed that the note in Southey 21, which links to M20_c1_p40, isn't in the table. Can we get it in there? I'd like to show this one as an example in my presentation on Saturday.

**Comment by HelenaSabel** [comment]
Hi @setriplette! I "hide" all those notes that had not translated materials because I wasn't sure about the best visualization for them. I'm going to make their content now in italics but if you have a better suggestion about their presentation, let me know. I could make them a mouse-over tooltip, for example.

**Comment by setriplette** [comment]
Hi Helena,

Italics works for me for now! I’m not sure what we’ll decide on later.

Thanks so much!

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 29, 2015, at 10:11 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @setriplettehttps://github.com/setriplette! I "hide" all those notes that had not translated materials because I wasn't sure about the best visualization for them. I'm going to make their content now in italics but if you have a better suggestion about their presentation, let me know. I could make them a mouse-over tooltip, for example.

**Comment by HelenaSabel** [comment]
Well, the italics look a bit weird because the note appears just after the word it was "attached" to...
If you are talking about the notes, might I suggest a passing comment on the one in the first chapter where Southey comments about the translation of "beata". He says that he doesn't want to use other words that would be more accurate because they are "sectarian words". However, he is missing that "beata perdida" is a pejorative expression. The word "perdida" doesn't have the meaning of "lost" at alll, but a emphatic one: "Pospuesto a un adjetivo, frecuentemente peyorativo, se usa para enfatizar su significado." (http://dle.rae.es)

**Comment by setriplette** [comment]
Hi Helena,

That’s a great point about “beata perdida”—I think it’s one of the places where we could argue that Southey made a mistranslation, or that his knowledge of Spanish wasn’t absolute.

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 29, 2015, at 10:25 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

Well, the italics look a bit weird because the note appears just after the word it was "attached" too...
If you are talking about the notes, might I suggest a passing comment on the one in the first chapter where Southey comments about the translation of "beata". He says that he doesn't want to use other words that would be more accurate because they are "sectarian words". However, he is missing that "beata perdida" is a pejorative expression. The word "perdida" doesn't have the meaning of "lost" at alll, but a emphatic one: "Pospuesto a un adjetivo, frecuentemente peyorativo, se usa para enfatizar su significado." (http://dle.rae.eshttp://dle.rae.es/)

**Comment by HelenaSabel** [comment]
Cells that have a not translated note inside them are underlined and if you click over it you'll get a tooltip with the contents of the note. If you want to go back to the italics, let me know.

**Comment by setriplette** [comment]
Ok! I’ll check it out!

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 29, 2015, at 11:45 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

Cells that have a not translated note inside them are underlined and if you click over it you'll get a tooltip with the contents of the note. If you want to go back to the italics, let me know.

**Comment by setriplette** [comment]
I’m seeing the underline but not the tooltip. I’m using chrome to open them.

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 29, 2015, at 11:45 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

Cells that have a not translated note inside them are underlined and if you click over it you'll get a tooltip with the contents of the note. If you want to go back to the italics, let me know.

**Comment by HelenaSabel** [comment]
Sorry! I forgot to push the new files: pull again and retry one more time. I'm sorry!

**Comment by setriplette** [comment]
Hi Helena,

The tooltip works now!

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 29, 2015, at 11:58 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry! I forgot to push the new files: pull again and retry one more time. I'm sorry!

**Comment by HelenaSabel** [comment]
And do you like it more than the italics?

**Comment by setriplette** [comment]
I think so—it looks pretty good in my slides. I’m sure Elisa will want to weigh in on the final form for the footnotes.

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Oct 29, 2015, at 3:00 PM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

And do you like it more than the italics?

**Comment by ebeshero** [comment]
I think it looks good, Helena! (And I know I was dubious of tooltips before.) But I think you found a good presentation solution that conveys how the notes are nested in the text. 

We will also, later on, extract all the notes in their own table to study--but we definitely need them here, first of all! 

When I finally get around to the reading views, I'll try to preserve Southey's italics around just the Spanish words--but I might do it with spans to hold his pseudomarkup of those phrases. (He isn't italicizing the whole note, though your italics did initially help to demonstrate the difference between main text and note). For the tables, what you've done seems just right for visually surveying where the notes fit into the translation units.

We're hearing right now a really good presentation on a Faust edition project with overlapping hierarchy issues something like ours--See https://github.com/faustedition/

Thank you!! Hugs,
Elisa
