### ISSUE TITLE
anchors at different levels

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#38]
I'm opening this issue because in Chapter Two, where we can find two notes with translated materials in them, it came to my attention that our stitchering system doesn't handle those in a satisfactory manner. Please find here the example I'm talking about: https://github.com/ebeshero/Amadis-in-Translation/commit/0e1c146f99cc595e0f177d145b0c5b67e6958a45
We need to consider that there can't be nested anchors at the same level, but a note creates a switch in the hierarchy. That way we can have things like:
`<anchor ana="start" corresp="#Montalvo"/>This is a clause with a word <note>Here Montalvo says: <anchor ana="start" corresp="#Montalvo"/>something<anchor ana="end"/></note> that it is annotated<anchor ana="end"/>`
I commented to that particular problem that we could use @corresp, but now that I think about it, there is no need to use any pointers: the `<anchor>` elements are at different elements due to the `<note>` so there is no ambiguity there. Any thoughts?

**Comment by ebeshero** [comment]
I'm about to repair this by altering the Schematron...and making sure it works on the Southey markup. Stay tuned for an update!

**Comment by ebeshero** [comment]
Resolved with my update of 11/3.
