### ISSUE TITLE
fork or branch?

### ISSUE THREAD

**Issue by sydb** [ebeshero/Amadis-in-Translation#39]
I've made some tweaks to the Schematron file (mostly just sorting out the use of atomic vs sequence comparison operators). Do you want to add me to the project so I can issue a pull request directly, or would you like me to fork the project and issue a pull request that way? (I don't know what the difference is in the interface, so don't ask)-:

**Comment by ebeshero** [comment]
@sydb I have just added you as a collaborator to Amadis, and that should mean you can contribute directly with push access to the repo.
