### ISSUE TITLE
clause IDs within chapter subdivisions

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#7]
I added a new stylesheet to number the clauses when there are subdivisions in the text. With the previous stylesheet, it would begin the numbering when there was a new paragraph (I've noticed it in chapter 21).
Since my proposal didn't deal with nested clauses, I added a rule to the schematron to detect them.

**Comment by ebeshero** [comment]
Altering the XSLT for xml:ids substantially: Discussion moved to: [Issue #8](https://github.com/ebeshero/Amadis-in-Translation/issues/8)

**Comment by ebeshero** [comment]
Revised the XSLT stylesheet.
