### ISSUE TITLE
resolved merge conflicts and cleaned up repo

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/Amadis-in-Translation#71]
@setriplette @HelenaSabel @msb81 I've just cleaned up some files in the repository: We had a duplicate directory from resolving a massive merge conflict from some weeks ago. I've just been inspecting the files and deleting that extra directory. I'm also deleting stale branches that I'm not using in this repo (so no more "Elisa" branch). Everyone should do a git pull from my remote origin at this point if you're all working in forks: 
````
git pull upstream master
````
Did you pull in anything? There should be some big changes. If you don't see them, here's how to make sure you're getting the most current changes from your fork:
* Check that you have your local github configured to find this remote origin (my repo) with this command:
````
git remote -v
````
If you don't have my remote origin set, enter this (with the https address of this repo on the web):
````
git remote add upstream https://github.com/ebeshero/Amadis-in-Translation.git
````
Then, try the command again: `git pull upstream master`

After about a year of working with forked repositories on this project, and working with branches in other projects, I think I'm okay with Helena and I just working in this repo, or in our own branches of it, and just doing pull requests to alert each other of changes.  Stacey, in your work with Madee, if you'd rather continue in a fork as you've been doing, and issue me a pull request when you're ready with changes, that system works, too. But we just need to make sure that everyone is pulling updates from the remote origin (*this* ebeshero repo) so that we aren't writing new material in old formats without the benefit of recent updates.  

Madee and Stacey, you'll have a workflow that involves a simple `git pull` first from your "Triplette fork", and then a `git pull upstream master` from me (as explained by @rjp43).

Stacey and I are about to be working on new material for Amadis in prep for a couple of presentations in June, so expect to see some new activity here! Let me know if you have any troubles with pulling in the changes, and note that Madee's new files mostly don't contain our markup--they're transcriptions only from what I can see (right?)

**Comment by HelenaSabel** [comment]
Hello all! My fork is now up-to-date. My apologies for looking as if I had disassociated from the project. I'll create a new branch in the main repo as soon as I have something to provide. 
@setriplette, let me know if there are any transcriptions you want me to review.
